import { mkdirSync, writeFileSync, existsSync, readFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { setTimeout as delay } from 'node:timers/promises';
import assert from 'node:assert/strict';
import { Hub, services, type Endpoints, type Service } from './hub.js';
import { Trace } from './trace.js';
import { startService } from './server.js';
import { QuoteStore } from './quotes.js';
import { startCluster } from './cluster.js';
import { runScenario } from './workflow.js';
import { runAgent, ollamaChat } from './agent.js';

const command = process.argv[2] ?? 'demo';
const database = process.env.QUOTE_DB ?? 'runtime/quotes.sqlite';
const output = process.env.OUTPUT_DIR ?? 'runtime';
const model = process.env.OLLAMA_MODEL ?? 'mistral:7b-instruct-v0.3-q4_K_M';
function endpointsFromEnv(): Endpoints {
  return Object.fromEntries(services.filter(s => process.env[`${s.toUpperCase()}_URL`]).map(s => [s, process.env[`${s.toUpperCase()}_URL`]]));
}

async function main() {
  if (command === 'serve') {
    const service = process.env.SERVICE as Service;
    if (!services.includes(service)) throw new Error('SERVICE must be inbox, crm, catalog or quotes');
    const authority = new Hub();
    const store = service === 'quotes' ? new QuoteStore(database) : undefined;
    if (store) { const endpoints = endpointsFromEnv(); delete endpoints.quotes; await authority.connect(endpoints); }
    const instance = await startService({ service, port: 3000, host: '0.0.0.0', store, authority });
    console.log(JSON.stringify({ service, status: 'ready', port: 3000 }));
    const stop = async () => { await instance.close(); await authority.close(); store?.close(); };
    process.once('SIGTERM', () => { void stop(); }); process.once('SIGINT', () => { void stop(); });
    return;
  }
  if (command === 'approve') {
    if (!process.argv[3]) throw new Error('Usage: approve <messageId>');
    const store = new QuoteStore(database);
    try { console.log(JSON.stringify(store.approve(process.argv[3]), null, 2)); } finally { store.close(); }
    return;
  }
  if (!['demo', 'verify', 'agent', 'worker'].includes(command)) throw new Error(`Unknown command: ${command}`);
  mkdirSync(output, { recursive: true });
  const cluster = Object.keys(endpointsFromEnv()).length ? null : await startCluster(database);
  const trace = new Trace(join(output, `${command}-${randomUUID()}.jsonl`));
  const hub = new Hub(trace);
  try {
    await hub.connect(cluster?.endpoints ?? endpointsFromEnv());
    if (command === 'agent') {
      const messageId = process.argv[3] ?? 'm-100';
      const quoteBefore = await hub.call('quotes__get', { messageId });
      const started = performance.now();
      const result = await runAgent(hub, messageId, ollamaChat(process.env.OLLAMA_URL ?? 'http://localhost:11434', model));
      const evidence = { mode: 'local_llm', model, generatedAt: new Date().toISOString(), runId: trace.runId,
        durationMs: Math.round(performance.now() - started), quoteExistedBeforeRun: quoteBefore !== null, result };
      writeFileSync(join(output, 'agent-result.json'), JSON.stringify(evidence, null, 2));
      console.log(JSON.stringify(evidence, null, 2));
      if (result.status === 'budget_exhausted') process.exitCode = 2;
    } else if (command === 'worker') {
      await worker(hub);
    } else {
      const results = [];
      for (const id of ['m-100', 'm-101', 'm-102', 'm-103', 'm-104']) results.push(await runScenario(hub, id));
      const replay = await runScenario(hub, 'm-100');
      assert.equal(results[0]!.quote?.totalExVatCents, 63600);
      assert.equal(results[1]!.reason, 'UNKNOWN_CUSTOMER');
      assert.equal(results[2]!.reason, 'MISSING_QUANTITY');
      assert.equal(results[3]!.quote?.totalExVatCents, 25800);
      assert.equal(results[4]!.reason, 'INSUFFICIENT_STOCK');
      assert.deepEqual(replay.quote, results[0]!.quote);
      const report = { mode: 'deterministic_integration', generatedAt: new Date().toISOString(), runId: trace.runId,
        checks: 6, passed: true, note: 'Real HTTP MCP calls; scenario decisions are scripted, not generated by an LLM.', results };
      writeFileSync(join(output, 'verification.json'), JSON.stringify(report, null, 2));
      console.log(JSON.stringify(report, null, 2));
    }
  } finally { await hub.close(); await cluster?.close(); }
}

async function worker(hub: Hub) {
  // One worker per state volume. Persist each terminal result atomically; restarts resume the remaining queue.
  const statePath = join(output, 'worker-state.json');
  const state: Record<string, { attempts: number; status: string; result?: unknown }> = existsSync(statePath) ? JSON.parse(readFileSync(statePath, 'utf8')) : {};
  let stopping = false;
  const controller = new AbortController();
  const stop = () => { stopping = true; controller.abort(); };
  process.once('SIGTERM', stop); process.once('SIGINT', stop);
  const chat = ollamaChat(process.env.OLLAMA_URL ?? 'http://localhost:11434', model);
  while (!stopping) {
    const queue = await hub.call<{ id: string }[]>('inbox__list', {});
    for (const { id } of queue) {
      if (stopping) break;
      const previous = state[id];
      if (previous && (previous.status !== 'retry' || previous.attempts >= 3)) continue;
      const attempts = (previous?.attempts ?? 0) + 1;
      try {
        const result = await runAgent(hub, id, chat);
        state[id] = { attempts, status: result.status, result };
      } catch (error) { state[id] = { attempts, status: 'retry', result: { error: error instanceof Error ? error.message : String(error) } }; }
      writeFileSync(`${statePath}.tmp`, JSON.stringify(state, null, 2)); renameSync(`${statePath}.tmp`, statePath);
      console.log(JSON.stringify({ messageId: id, ...state[id] }));
    }
    if (process.env.WORKER_ONCE === '1') return;
    if (!stopping) await delay(60_000, undefined, { signal: controller.signal }).catch(error => { if (error.name !== 'AbortError') throw error; });
  }
}

main().catch(error => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
